
import samsung from "./Images/samsungm21.jpg"
const products=
    [{
        id:1,
        name:"Samsung M21",
        img:samsung,
        price:100,
        quantity:1
    },
    {
        id:2,
        name:"Apple",
        img:samsung,
        price:200,
        quantity:1
    },{
        id:3,
        name:"Redmi",
        img:samsung,
        price:300,
        quantity:1
    },
    {
        id:4,
        name:"Mi",
        img:samsung,
        price:400,
        quantity:1
    },
    {
        id:5,
        name:"Nokia",
        img:samsung,
        price:100,
        quantity:1
    },
    {
        id:6,
        name:"Nokia",
        img:samsung,
        price:200,
        quantity:1
    },
    {
        id:7,
        name:"Nokia",
        img:samsung,
        price:300,
        quantity:1
    },
    {
        id:8,
        name:"Nokia",
        img:samsung,
        price:400,
        quantity:1
    },
    {
        id:9,
        name:"Nokia",
        img:samsung,
        price:100,
        quantity:1
    },
    {
        id:10,
        name:"Nokia",
        img:samsung,
        price:200,
        quantity:1
    },
    {
        id:11,
        name:"Nokia",
        img:samsung,
        price:300,
        quantity:1
    },
    {
        id:12,
        name:"Nokia",
        img:samsung,
        price:400,
        quantity:1
    },
    {
        id:13,
        name:"Nokia",
        img:samsung,
        price:500,
        quantity:1
    },
    {
        id:14,
        name:"iPhone",
        img:samsung,
        price:600,
        quantity:1
    },
    {
        id:15,
        name:"Nokia",
        img:samsung,
        price:400,
        quantity:1
    }
    ]
export default products